config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    get :profile
    resources :messages, only: [:new, :create, :show] #-> domain.com/users/:user_id/messages/new
  end

  resources :messages do
    get :outbox, action: "outbox", type: "sendmessages", on: :collection #-> domain.com/messages/outbox
    get :inbox, action: "inbox", type: "recivmessages", on: :collection #-> domain.com/messages/inbox
    get :show, action: "show", type: "recivmessages", on: :collection #-> domain.com/messages/allmes
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User",  foreign_key: "sender_id"
  belongs_to :reciver, class_name: "User", foreign_key: "reciver_id"

  default_scope -> { order(created_at: :desc) }

  validates :body, presence: true, length: { maximum: 500 }
  validates :sender_id, presence: true
  validates :reciver_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sendmessages, :foreign_key => :sender_id, class_name: 'Message'
  has_many :recivmessages, :foreign_key => :reciver_id, class_name: 'Message'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = current_user.sendmessages
  end

  def new
    @message = current_user.sendmessages.new
    @chosen_reciver = User.find_by(id: params[:reciver_id].to_i) if params[:reciver_id]
  end

  def create

    @message = current_user.sendmessages.create(permitted_params[:message].merge!(sender_id: current_user.id))
    if  @message.save
      flash[:notice] = "Message sent!"
      redirect_to "show"
    else
      flash[:error] = @message.errors.full_messages.to_sentence
      render "new"
    end
  end

  def destroy
    @message = current_user.messages.destroy params[:id]
  end

  def show
    @allmessages = current_user.sendmessages + current_user.recivmessages
  end

  def outbox
    @outmessage = current_user.sendmessages
  end

  def inbox
    @inmessage = current_user.recivmessages
  end

  private

  def permitted_params
    params.permit( message: [ :body, :reciver_id ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @users = User.paginate(page: params[:page])
  end
  def new
  end

  def show
    @user = User.all
  end

  def edit
  end

  def destroy
  end

  def sender
    @user = User.find(params[:id])
  end

  def reciver
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(text)
    content_for(:page_header) { text.to_s }
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def reciver_options(chosen_reciver = nil)
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'  #{'selected' if user == chosen_reciver}>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">NewMessage</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "NewMessage", "#", class: "navbar-brand" %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav pull-right">
              <% if user_signed_in? %>
                  <li>
                    <%= link_to "Hi, #{current_user.name}" %>
                  </li>
                  <li>
                    <%= link_to "Edit profile", "#"  %>
                  </li>
                  <li>
                    <%= link_to "Users", users_path %>
                  </li>
                  <li>
                    <%= link_to "Send message", new_message_path %>
                  </li>
                  <li>
                    <%= link_to "AllMessage", messages_path %>
                  </li>
                  <li>
                    <%= link_to "Inbox", inbox_messages_path %>
                  </li>
                  <li>
                    <%= link_to "Outbox", outbox_messages_path %>
                  </li>
                  <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete	  %>
                  </li>

              <% else %>
                  <li>
                    <%= link_to "Signin", new_user_session_path %>
                  </li>
                  <li>
                    <%= link_to "Signup", new_user_registration_path %>
                  </li>

              <% end %>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
          </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>

  <title>MewMessage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- shiv here -->

</head>

<body>

<%= render 'layouts/nav' %>

<div class="container">
  <!-- flash messages here -->
  <%= yield %>
</div>
<audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio>
</body>

</html>

app/views/messages/create.html.erb
<h1>Your message send</h1>

<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end -%>

app/views/messages/inbox.html.erb
<p>Find me in app/views/message/show.html.erb</p>
<p>Find me in app/views/message/show.html.erb</p>

<h3>IN messages</h3>

<ol class="messages">
  <% @inmessage.each do |inmessage| %>
      <li>
        <span class="sender">From: <%= inmessage.sender.name %> =></span>
        <span class="sender">To: <%= inmessage.reciver.name %></span>&nbsp &nbsp
        <span class="content">Text: <%= inmessage.body %></span>&nbsp &nbsp
        <span class="create">Create: <%= inmessage.created_at %></span>
      </li>
  <% end %>
</ol>

app/views/messages/index.html.erb
<h1>Message was not posted</h1>

app/views/messages/new.html.erb
<h1>Message#new</h1>


<%= form_tag messages_path, method: :post do %>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[reciver_id]', 'Выберите получателя' %>
    <%= select_tag 'message[reciver_id]',reciver_options(@chosen_reciver),  class: 'form-control chosen-it' %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-primary' %>

  <% end %>

app/views/messages/outbox.html.erb
<p>Find me in app/views/message/show.html.erb</p>
<p>Find me in app/views/message/show.html.erb</p>

<h3>OUT messages</h3>

    <ol class="messages">
      <% @outmessage.each do |outmessage| %>
          <li>
            <span class="sender">From:<%= outmessage.sender.name %> =></span>
            <span class="reciver">To: <%= outmessage.reciver.name %></span>&nbsp &nbsp &nbsp
            <span class="content">Text: <%= outmessage.body %></span>&nbsp &nbsp &nbsp
            <span class="create">Create: <%= outmessage.created_at %></span>
          </li>
      <% end %>
    </ol>

app/views/messages/show.html.erb
<p>Find me in app/views/message/show.html.erb</p>
<p>Find me in app/views/message/show.html.erb</p>

<h3>ALL messages</h3>


  <ul class="messages">
    <% @allmessages.each do |message| %>
      <li>

        <span class="sender">From: <%= message.sender.name %>=></span>&nbsp &nbsp &nbsp
        <span class="reciver">To: <%= message.reciver.name %></span> &nbsp &nbsp &nbsp
        <span class="content"><%= message.body %></span>&nbsp &nbsp
        <span class="create">Create: <%= message.created_at %></span>
      </li>
    <% end %>
  </ul>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="col-md-6">
  <% provide(:title, 'All users') %>
  <h1>All users</h1>

  <%= will_paginate %>

  <table>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @users.each do |user| %>
        <tr>
          <td><%=link_to user.name, 'users#allmes' %></td>
          <td><%=link_to 'Sent Message', new_message_path(reciver_id: user.id), class: "btn btn-primary btn-xs start-conversation",
                  "data-sid" => current_user.id, "data-rip" => user.id%></td>
        </tr>
    <% end %>
  </table>

  <br />
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>